dbMemo "SQL" ="SELECT Orders.[Order ID], Orders.[Employee ID], Orders.[Customer ID], Orders.[Or"
    "der Date], Orders.[Shipped Date], [Order Price Totals].[Price Total] AS [Sub Tot"
    "al], Orders.[Shipping Fee], Orders.Taxes, [Sub Total]+[Shipping Fee]+[Taxes] AS "
    "[Order Total], Orders.[Ship Name], Orders.[Ship Address], Orders.[Paid Date], [O"
    "rders Status].[status name] AS Status\015\012FROM [Orders Status] RIGHT JOIN (Or"
    "ders LEFT JOIN [Order Price Totals] ON Orders.[Order ID]=[Order Price Totals].Or"
    "derID) ON [Orders Status].[Status ID]=Orders.[Status ID]\015\012ORDER BY Orders."
    "[Order ID] DESC;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
