dbMemo "SQL" ="SELECT T_TradTexte.Trad_ID, T_TradTexte.PropNom, T_TradTexte.PropTexte, T_TradTe"
    "xte.DateMaJ, iif(ModPropTexte=true,\"=\",null) AS Modif, iif(Scanner=false,\"=\""
    ",null) AS Scan\015\012FROM T_TradTexte\015\012WHERE (((T_TradTexte.DefLangue)=Tr"
    "ue));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
