dbMemo "SQL" ="SELECT T_Objets.ObjetApp\015\012FROM T_Objets\015\012GROUP BY T_Objets.ObjetApp\015"
    "\012ORDER BY T_Objets.ObjetApp;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
